monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  rotating_file
            max_files: 10
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: g.ponty@dev-web.io
            to_email:   g.ponty@dev-web.io
            subject:    "[PAMS PROD] An Error Occurred!"
            level:      debug
